In [29]:
import pandas as pd
import numpy as np

In [2]:
df=pd.read_csv('regression_insurance.csv')

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1338 entries, 0 to 1337
Data columns (total 7 columns):
 #   Column    Non-Null Count  Dtype  
---  ------    --------------  -----  
 0   age       1338 non-null   int64  
 1   sex       1338 non-null   object 
 2   bmi       1338 non-null   float64
 3   children  1338 non-null   int64  
 4   smoker    1338 non-null   object 
 5   region    1338 non-null   object 
 6   charges   1338 non-null   float64
dtypes: float64(2), int64(2), object(3)
memory usage: 73.3+ KB


In [4]:
df

age     sex     bmi  children smoker     region      charges
0      19  female  27.900         0    yes  southwest  16884.92400
1      18    male  33.770         1     no  southeast   1725.55230
2      28    male  33.000         3     no  southeast   4449.46200
3      33    male  22.705         0     no  northwest  21984.47061
4      32    male  28.880         0     no  northwest   3866.85520
...   ...     ...     ...       ...    ...        ...          ...
1333   50    male  30.970         3     no  northwest  10600.54830
1334   18  female  31.920         0     no  northeast   2205.98080
1335   18  female  36.850         0     no  southeast   1629.83350
1336   21  female  25.800         0     no  southwest   2007.94500
1337   61  female  29.070         0    yes  northwest  29141.36030

[1338 rows x 7 columns]

In [9]:
from sklearn.preprocessing import LabelEncoder

In [6]:
# !pip install scikit-learn -U

In [10]:
t = LabelEncoder()

In [11]:
t.fit_transform(df.sex)

array([0, 1, 1, ..., 0, 0, 0])

In [12]:
df['sex'] = t.fit_transform(df.sex)

In [13]:
df['region'] = t.fit_transform(df.region)

In [15]:
df['smoker'] = t.fit_transform(df.smoker)

In [16]:
df

age  sex     bmi  children  smoker  region      charges
0      19    0  27.900         0       1       3  16884.92400
1      18    1  33.770         1       0       2   1725.55230
2      28    1  33.000         3       0       2   4449.46200
3      33    1  22.705         0       0       1  21984.47061
4      32    1  28.880         0       0       1   3866.85520
...   ...  ...     ...       ...     ...     ...          ...
1333   50    1  30.970         3       0       1  10600.54830
1334   18    0  31.920         0       0       0   2205.98080
1335   18    0  36.850         0       0       2   1629.83350
1336   21    0  25.800         0       0       3   2007.94500
1337   61    0  29.070         0       1       1  29141.36030

[1338 rows x 7 columns]

In [ ]:
y = df.charges 
x = df.iloc[:,:-1]

In [21]:
y = y.values
x = x.values

AttributeError: 'numpy.ndarray' object has no attribute 'values'

In [22]:
from sklearn.linear_model import LinearRegression

In [23]:
model = LinearRegression()

In [25]:
model.fit(x, y)

LinearRegression()

In [26]:
model.predict(x)

array([25111.24186363,  3687.60517284,  6963.14570669, ...,
        4363.66236622,  1106.98661296, 37013.72809551])

In [31]:
np.array([20, 0, 30.1, 0, 1, 2]).shape

(6,)

In [33]:
np.array([20, 0, 30.1, 0, 1, 2]).reshape(1,-1).shape

(1, 6)

In [34]:
model.predict(np.array([20, 0, 30.1, 0, 1, 2]).reshape(1,-1))

array([26453.82424598])

In [35]:
import joblib
joblib.dump(model, "research.joblib")

['research.joblib']

In [36]:
m = joblib.load('research.joblib')

In [37]:
m

LinearRegression()